from pathlib import *
path = Path(__file__).parent
TYPE_FILE = {
	".py": "python",
	".python": "python",
	".cpp": "c++",
	".c": "c++",
	".java": "java",
	".cs": "c#",
	".sql": "sql",
	".asm": "asm",
	".r": "R",
	".lua": "Lua",
	".go": "Go",
	".rs": "Rust",
	".swift": "Swift",
	".kt": "Kotlin",
	".bat": "Batch",
	".sh": "Shell",
	".ps1": "PowerShell",
}

TYPE_RUN_SYNTAX = {
	".py": ["python", "-u", "{file}"],
	".cpp": ["g++", "-o", "{out}", "{file}"],
	".c": ["gcc", "-o", "{out}", "{file}"],
	".java": ["java", "{file}"],
	".cs": ["dotnet", "script", "{file}"],
	".sql": "",
	".asm": "",
	".r": ["Rscript", "{file}"],
	".lua": ["lua", "{file}"],
	".go": ["go", "run", "{file}"],
	".rs": ["rustc", "{file}", "-o", "{out}"],
	".swift": ["swift", "{file}"],
	".kt": ["kotlin", "{file}"],
	".bat": ["cmd", "/c", "{file}"],
	".sh": ["bash", "{file}"],
	".ps1": ["{file}"],
}

ICON_LANGUESE = {
	"c": f"{path}/icon/icon_L/icon_languese_c.png",
    "cpp": f"{path}/icon/icon_L/icon_languese_cpp.png",
    "python": f"{path}/icon/icon_L/icon_languese_python.png",
    "java": f"{path}/icon/icon_L/icon_languese_java.png",
    "cs": f"{path}/icon/icon_L/icon_languese_cs.png",
    "sql": f"{path}/icon/icon_L/icon_languese_sql.png",
    "asm": f"{path}/icon/icon_L/icon_languese_asm.png",
    "r": f"{path}/icon/icon_L/icon_languese_R.png",
    "lua": f"{path}/icon/icon_L/icon_languese_lua.png",
    "go": f"{path}/icon/icon_L/icon_languese_go.png",
    "rs": f"{path}/icon/icon_L/icon_languese_rust.png",
    "swift": f"{path}/icon/icon_L/icon_languese_swift.png",
    "kt": f"{path}/icon/icon_L/icon_languese_kotlin.png",
	"bat": f"{path}/icon/icon_L/icon_languese_batch.png",
	"sh": f"{path}/icon/icon_L/icon_languese_powershell.png",
    "ps1": f"{path}/icon/icon_L/icon_languese_powershell.png",
}
